<?php
$title = 'Add new SCG Business';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php

$business = $form->get('business');
$business->setAttribute('class', 'form-control');
$business->setAttribute('placeholder', 'Business Title');

$holding = $form->get('holding');
$holding->setAttribute('class', 'form-control');
$holding->setAttribute('placeholder', 'Holding %');

$telephone = $form->get('telephone');
$telephone->setAttribute('class', 'form-control');
$telephone->setAttribute('placeholder', 'Telephone Number');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('scg', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($business) ?>
    <?= $this->formElement($business) ?>
    <?= $this->formElementErrors()->render($business, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($holding) ?>
    <?= $this->formElement($holding) ?>
    <?= $this->formElementErrors()->render($holding, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($telephone) ?>
    <?= $this->formElement($telephone) ?>
    <?= $this->formElementErrors()->render($telephone, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
